Add live theme switching support
jenkinsci/material-theme-plugin pull request #11
Opened 2022-02-21 09:04 UTC by timja

See https://github.com/jenkinsci/theme-manager-plugin/pull/75

All themes are now loaded on every page, the active theme is controlled by a `data` attribute on the `html` element.

This PR isn't complete yet needs some more refactoring, it's a lot more difficult than the others, also a bit worried that the files are too heavy ~3500 lines each. ~390kb.

Will see if I can find the time to get something a bit nicer

fyi @timbrown5

2022-02-24 08:27 UTC, timja commented on pom.xml
> +    <version>4.35</version>
```suggestion
    <version>4.37</version>
```

2022-02-24 08:27 UTC, timja commented on pom.xml
> +    <jenkins.version>2.336-rc32081.db_eed62c0c0e</jenkins.version>
```suggestion
    <jenkins.version>2.336</jenkins.version>
```

2022-02-24 08:27 UTC, timja commented on pom.xml
> +      <version>0.7-rc94.26a_5398f092d</version>
```suggestion
      <version>1.0</version>
```

2022-02-24 08:28 UTC, timja commented on pom.xml
> +    <connection>scm:git:git://github.com/${gitHubRepo}.git</connection>
```suggestion
    <connection>scm:git:https://github.com/${gitHubRepo}.git</connection>
```

2022-02-24 08:29 UTC, timja commented
@timbrown5 FYI material theme is looking a little broken on recent weeklies due to some icon changes :).

But this is unrelated to that

2022-03-03 12:42 UTC, timbrown5 requested changes

2022-03-03 12:42 UTC, timbrown5 commented on pom.xml
> +    <jenkins.version>2.336</jenkins.version>
As this plugin replaces most of the older Jenkins icons This needs to be pinned for a family of releases.
0.3.x - Supports pre 2.289.1 (specifically before `Add modern icons: build status and weather. ([pull 5065](https://github.com/jenkinsci/jenkins/pull/5065), [pull 5392](https://github.com/jenkinsci/jenkins/pull/5392)`)) 
0.4.x - supports `2.289.1`+ (unless there are significant Jenkins Icon changes).
0.5.x - will support the next big UI change (possible https://github.com/jenkinsci/jenkins/pull/6307).

My hope is that by doing this I can fix critical issues for users stuck on older Jenkins versions, whilst also not breaking any new icon changes (although it sounds like it's a bit broken on recent Jenkins releases?).
As such, can you leave this as `2.289.1`, so it's the minimum supported version?

That said, if this version update is required to support dependencies (e.g. Theme manager) then can you change the version to 0.5.0 (and then 0.6.x will need to support the next UI change).

2022-03-03 14:12 UTC, timja commented on pom.xml
> +    <revision>0.4.2</revision>
```suggestion
    <revision>0.5.0</revision>
```

2022-03-03 14:13 UTC, timja commented on pom.xml
> +    <jenkins.version>2.336</jenkins.version>
It's required https://github.com/jenkinsci/theme-manager-plugin/blob/795dd3b2c8d2a7a89a7e86f47c231bd271fc4141/pom.xml#L17

Checkbox structure changed in 2.335 and there was an improvement in 2.336 required for theme manager.

2022-03-15 10:59 UTC, timbrown5 approved these changes

2022-03-15 10:59 UTC, timbrown5 commented on pom.xml
> +    <jenkins.version>2.336</jenkins.version>
Thanks, just checking if this version change will cause issues for #13 (just to know the order of merging).
The likelihood is that someone will need to update their PR. I will prefer yours you were first (unless #13 is stuck on an older version).

2022-03-15 10:59 UTC, merged